@startmindmap "Monitoring"

'Icons https://plantuml.com/sprite


caption The Azure Landscape - Security
title The Azure Landscape - Monitoring

center footer The Azure landscape as mapped out in AZ-204

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Misc/all.puml
!include osaPuml/Server/all.puml
!include osaPuml/Site/all.puml

<style>

    mindMapDiagram {
        
        LineColor lightblue
        RoundCorner 5
        BackgroundColor white
        Shadowing 2.0

        ' rootNode {
        '     LineColor white
        '     BackgroundColor white
        ' }

        node {
            LineColor blue
            BackgroundColor lightblue
        }
        :depth(0) {
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor blue
            BackgroundColor white
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

'=========================================================
'Root (User Audit)
'=========================================================
+ <$osa_ics_thermometer,scale=1.5>

++ Azure Monitor
+++_ Overall monitoring system
+++_ Monitor all your applications within a resource group or subscription

+++ Application Insights
++++_ Feature of Azure Monitor... both log to Azure Analytics Workspace
++++_ Monitor a single web or desktop application
++++_ A feature of Azure Monitor

++ Visual Studio App Center
+++_ Monitor a single mobile application

++ Network Watcher
+++_ Find the next hop, troubleshoot IP addresses, VM access issues

++ Security Center
+++_ Monitors all your services. Which one's are less secure and what can you do to fix it?
++++ Advisor
+++++_ Extension that monitors and recommends for performance, availability and cost

++ Azure Sentinel

@endmindmap 