@startmindmap "Service Tiers"

'Icons https://plantuml.com/sprite


caption The Azure Landscape - Service Tiers
title The Azure Landscape - Service Tiers

center footer The Azure landscape as mapped out in AZ-204

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Misc/all.puml
!include osaPuml/Server/all.puml
!include osaPuml/Site/all.puml

<style>

    mindMapDiagram {
        
        LineColor lightblue
        RoundCorner 5
        BackgroundColor white
        Shadowing 2.0

        ' rootNode {
        '     LineColor white
        '     BackgroundColor white
        ' }

        node {
            LineColor blue
            BackgroundColor lightblue
        }
        :depth(0) {
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor blue
            BackgroundColor white
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

'=========================================================
'Root (User Audit)
'=========================================================
+ <$osa_user_audit,scale=1.5>

'=========================================================
'App Service
'=========================================================
++ App Service (Web Apps)
+++_  **Shared** Compute\nAllocated CPU quotas\nNo Scaling
++++_  **Free**
++++_  **Shared**
+++_ **Dedicated** Compute\nDedicated Azure VMs
++++_  **Basic**
++++_  **Standard** - (and above have Deployment Slots)
++++_  **Premium**
++++_  **Premium**V2
++++_  **Premium**V3
+++_  **Isolated**\n**Single tenant**\nDedicated tiers &\nNetwork isolation
++++_  **Isolated**
++++_  **Isolated**V2 (ASE)

'=========================================================
'Functions
'=========================================================
-- Functions
---_ **Consumption**
----_ (auto scaling, pay per use, **Serverless**)
---_ **Premium**
----_ (pre-warmed workers, VN connectivity, powerfull VMs)
---_ **Dedicated**
----_ (App Service Plan, long running scenarios)
---_ ASE (App Service Environment)
----_ Fully isolated and runs at high scale
---_ Kubernetes (Direct or Azure Arc)
----_ Fully isolated run on Kubernetes platform

'=========================================================
'Containers
'=========================================================
-- Containers
--- Azure Container Registry
----_ Paid per day
----_  **Basic**,  **Standard**,  **Premium** (supports replication)
----_  **Basic**
-----_ Cost optimized entry point for developers
-----_ Same programmatic capabilities as  **Standard** and  **Premium**
-----_ Storage and image throughput appropriate for lower usage
----_  **Standard**
-----_ Should satisfy the needs of most production scenarios
----_  **Premium**
-----_ Highest amount of storage and concurrent operations, enabling high-volume scenarios
-----_ Geo replication
-----_ Content trust (image tag signing)
-----_ Private endpoints (restricted access)

--- Azure Container Apps
----_  **Free** allowance
-----_ First 180 000 vCPU seconds
-----_ 360 000 GiB seconds of memory
-----_ 2 000 000 requests
----_ **Serverless** (can scale to zero)
----_ Pay per vCPU second and memory used
----_ Per million requests

--- Container Instances
----_  **Standard**
-----_ Hypervisor level isolation
-----_ recommended for most workloads
----_ Confidential (development policy)
-----_ In-use memory encryption
-----_ Hardware level isolation

'=========================================================
'Blog Storage
'=========================================================
-- Blob Storage
---_ General Purpose V2
----_ Archived, Cool, Hot
---_ **Premium**
----_ Optimized for fast interaction

'=========================================================
'Cosmos DB
'=========================================================
-- Cosmos DB
---_ Provisioned Throughput
----_ Per-hour basis for the RU/s provisioned
---_ **Serverless**
----_ Per-hour basis for the number of RUs consumed


'=========================================================
'Redis Caching
'=========================================================
++ Azure Cache\nfor Redis
+++_  **Basic**
++++_ OSS Redis, Single VM, no SLA
++++_ dev/test non-critical workloads
+++_  **Standard**
++++_ OSS Redis, replicate to 2 VMs
+++_  **Premium**
++++_ OSS Redis, high performance
++++_ Higher throughput, availability.
++++_ Lower latency, more powerful VMs
+++_  **Enterprise**
++++_ Redis Labs  **Enterprise**, Higher performance + availability
++++_ Redis modulesDedicated Ti
+++_  **Enterprise** Flash
++++_ Redis Labs Enterpise, non-volatile memory
++++_ Cost effective large caches

'=========================================================
'Azure CDN
'=========================================================
++ Azure CDN
+++_ **Standard**
++++_ Content delivery optimized
++++_ CDN  **Standard** from Verizon (S1)
++++_ CDN  **Standard** from Akamai (S2)
++++_ Microsoft (classic) (S3)
+++_ **Premium**
++++_ Security optimized

'=========================================================
'Service Bus
'=========================================================
++ Service Bus
+++_ **Standard**
++++_ Pay as you go pricing. Variable throughput and latency.
+++_ **Premium**
++++_ Fixed pricing. High throughput and predictable performance.


'=========================================================
'Key Vaults
'=========================================================

++ Key Vaults
+++_ **Standard**
++++_ encrypts with a softrware key
+++_ **Premium**
++++_ includes hardware security module(HSM)-protected keys

'=========================================================
'API Management
'=========================================================

++ API Management
+++_ Developer (No SLA)
+++_ Basic (99.95% SLA)
+++_ **Standard** (99.95% SLA)
+++_ **Premium** (99.95% or 99.99% SLA)
+++_ **Consumption** (99.95% SLA)
@endmindmap 