@startmindmap "Service Tiers"

'Icons https://plantuml.com/sprite


caption The Azure Landscape - Logging and Monitoring
title The Azure Landscape - Logging and Monitoring

center footer The Azure landscape as mapped out in AZ-204

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Misc/all.puml
!include osaPuml/Server/all.puml
!include osaPuml/Site/all.puml

<style>

    mindMapDiagram {
        
        LineColor lightblue
        RoundCorner 5
        BackgroundColor white
        Shadowing 2.0

        ' rootNode {
        '     LineColor white
        '     BackgroundColor white
        ' }

        node {
            LineColor blue
            BackgroundColor lightblue
        }
        :depth(0) {
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor blue
            BackgroundColor white
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

'=========================================================
'Root (User Audit)
'=========================================================
+ <$osa_user_audit,scale=1.5>

'=========================================================
'Functions
'=========================================================

-- Functions
--- Logs
--- Monitoring

'=========================================================
'Redis Caching
'=========================================================

-- Redis Caching
--- Logs
--- Monitoring

'=========================================================
'CDN
'=========================================================

-- CDN
--- Logs
--- Monitoring

'=========================================================
'Key Vaults
'=========================================================

-- Key Vaults
--- Logs
--- Monitoring
----_ Archive to storage account
----_ Stream to event hub
----_ Send logs to Azure Monitor logs
---_ Turn on monitoring and alerts


'=========================================================
'Message Queues
'=========================================================

-- Message Queues
--- Logs
--- Monitoring

'=========================================================
'Azure Service Bus
'=========================================================

-- Azure Service Bus
--- Logs
--- Monitoring

'=========================================================
'Event Grid
'=========================================================

-- Event Grid
--- Logs
--- Monitoring

'=========================================================
'Event Hubs
'=========================================================

-- Event Hubs
--- Logs
--- Monitoring

'=========================================================
'Container Registry
'=========================================================

++ Container Registry
+++ Logs
+++ Monitoring

'=========================================================
'Container Apps
'=========================================================

++ Container Apps
+++ Logs
+++ Monitoring

'=========================================================
'Container Instances
'=========================================================

++ Container Instances
+++ Logs
+++ Monitoring

'=========================================================
'Web Apps
'=========================================================

++ Web Apps
+++ Logs
+++ Monitoring

'=========================================================
'Storage
'=========================================================

++ Storage
+++ Logs
+++ Monitoring

'=========================================================
'Cosmos DB
'=========================================================

++ Cosmos DB
+++ Logs
+++ Monitoring

'=========================================================
'API Management
'=========================================================

++ API Management
+++ Logs
+++ Monitoring



@endmindmap 