@startmindmap "Course"

'Icons https://plantuml.com/sprite


caption The Azure Landscape - Course
title The Azure Landscape - Course

center footer The Azure landscape as mapped out in AZ-204

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Misc/all.puml
!include osaPuml/Server/all.puml
!include osaPuml/Site/all.puml

<style>

    mindMapDiagram {
        
        LineColor lightblue
        RoundCorner 5
        BackgroundColor white
        Shadowing 2.0

        ' rootNode {
        '     LineColor white
        '     BackgroundColor white
        ' }

        node {
            LineColor blue
            BackgroundColor lightblue
        }
        :depth(0) {
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor blue
            BackgroundColor white
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

'=========================================================
'Root (User Audit)
'=========================================================
+ <$osa_user_white_hat,scale=1.5>

++ Implement Azure App Service Web Apps
++ Implement Azure Functions
+++ Triggers and Bindings

++ Learn containerized solutions
+++ Azure Container Registry
+++ Azure Container Instances
+++ Azure Container Apps

++ Implement user authentication and authorization
+++ Microsoft Identity Platform
+++ MSAL
+++ Shared Access Signatures
+++ Stored Access Policies
+++ Microsoft Graph

++ Implement secure Azure solutions
+++ Azure Key Vault
+++ Managed Identities
+++ Azure App Configuration

-- Implement API Management
-- Troubleshoot solutions and Application Insights
-- Implement caching for solutions
--- Azure Cache for Redis
--- Azure Content Delivery Network (CDN)

-- Develop event-based solutions
--- Event Grid
--- Event Hubs
-- Develop message-based solutions
--- Service Bus
--- Storage Queue

-- Develop Solutions that use Blob Storage
-- Develop Solutions that use Cosmos DB

@endmindmap 