@startmindmap "Client Libraries"

'Icons https://plantuml.com/sprite


caption The Azure Landscape - Security
title The Azure Landscape - Security

center footer The Azure landscape as mapped out in AZ-204

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Misc/all.puml
!include osaPuml/Server/all.puml
!include osaPuml/Site/all.puml

<style>

    mindMapDiagram {
        
        LineColor lightblue
        RoundCorner 5
        BackgroundColor white
        Shadowing 2.0

        ' rootNode {
        '     LineColor white
        '     BackgroundColor white
        ' }

        node {
            LineColor blue
            BackgroundColor lightblue
        }
        :depth(0) {
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor blue
            BackgroundColor white
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

'=========================================================
'Root (User Audit)
'=========================================================
+ <$osa_user_white_hat,scale=1.5>

-- Queues
--- Azure Service Bus
----_ Shared Access Signatures (SAS)
----_ Role-based Access Control (RBAC)
----_ Managed Identities for Azure Resources
--- Storage Queues
----_ Shared Access Signatures (SAS)
----_ Role-based Access Control (RBAC)
----_ Managed Identities for Azure Resources


++ App Services\n(Web Apps)
+++_ Provider integration.\nFederated identity\nFor example, Azure AD, Facebook, Google, Twitter.
+++_ Built-in Authentication and authorization module (requires no SDKs)
+++_ Authentiation Flow:
++++_ Without Provider SDK (browser)\nserver-directed-flow
++++_ With Provider SDK (browserless)\nclient-directed flow

++ Key Vaults
+++_ RBAC for Vault Management
+++_ Key vault access policy for accessing vault data
+++ Tiers
++++_ Standard is software protected
++++_ Premium can be hardware protected (HSMs)
+++_ Authenticate to using:
++++_ **Managed Identities**
++++_ App Registration\nNot recomended because\nof key rotation requirements:
+++++_ Service Principal and certificate
+++++_ Service Principal and secret
+++ Transit:
++++_ TLS
++++_ Perfect Forward Secrecy (PFS)
++++_ RSA-based 2,048-bit encryption key lengths

'=========================================================
'Functions
'=========================================================

'++ Functions
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Redis Caching
'=========================================================

'++ Redis Caching
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'CDN
'=========================================================

'++ CDN
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Key Vaults
'=========================================================

'++ Key Vaults
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Message Queues
'=========================================================

'++ Message Queues
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Azure Service Bus
'=========================================================

'++ Azure Service Bus
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Event Grid
'=========================================================

'++ Event Grid
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Event Hubs
'=========================================================

'++ Event Hubs
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Container Registry
'=========================================================

'++ Container Registry
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Container Apps
'=========================================================

'++ Container Apps
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Container Instances
'=========================================================

'++ Container Instances
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Web Apps
'=========================================================

'++ Web Apps
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Storage
'=========================================================

'++ Storage
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'Cosmos DB
'=========================================================

'++ Cosmos DB
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

'=========================================================
'API Management
'=========================================================

'++ API Management
'+++_ Role-based Access Control (RBAC)
'+++_ Share Access Signatures (SAS)
'+++_ <s>Managed Identities</s>

@endmindmap 