@startmindmap "App Service"

caption App Service Overview
title App Service Overview

center footer App Service as mapped out in AZ-204

+ Azure App Service
++ Hosting Options
+++ Web Apps
++++_ for hosting web applications
+++ Mobile Apps
++++_ for mobile applications on iOS and Android
+++ API Apps
++++_ for building RESTful APIs
+++ Function Apps
++++_ for serverless applications with Azure Functions

+ Scaling
++ Scale up/down
+++_ resources = no. of cores and RAM available
+++_ Change pricing tier of plan
++ Scale out/in
+++_ Increase or decrease no. of machine (host) instances

+ Deployment
++ Deployment Slots
+++_ Standard service plan and above
+++_ Live apps with own host names
+++_ Allows for swapping
++ Continuous integration
+++_ Auto-sync code and any future changes

+ Linux and containers
++ Support languages
+++_ Node.js, Java, PHP, Python, Ruby
+++_ **or** deploy as custom container
+++_ **az webapp list-runtimes --os-type linux**
+++ Limitations
++++_ Not supported on Shared Tier
++++_ Some features not available to Linux Apps
++++_ Storage volumes have higher disk latency

@endmindmap