@startmindmap
* Azure Container Instances (ACI)
** Benefits
***_ Fast startup
***_ Container access - IP Address and FQDN
***_ Hypervisor-level security
***_ Minimum customer data in order to run
***_ Custom sizes for CPU cores and memory
***_ Mount Azure File shares directly to container
***_ Linux and Windows support using same API
*** Shortcomings
****_ Falls short of...
*****_ discovery across multiple containers
*****_ Full container orchestration
*****_ Automatic scaling and coordinated application upgrades
*****_ Recommends Azure Kubernetes Service (AKS) recommended


** Container groups
***_ Collection of containers...\n ...scheduled on the same host machine
***_ Share lifecycle, resources,\nlocal network, storage volumes
**** Network
*****_ Assigned a single DNS name label\n...and public IP address
*****_ Expose ports\n(from one or more container instances)
*****_ Communicate with each other using\nlocalhost
*****_ Port mapping not supported
**** Volume mounts 
*****_ Azure file shares
*****_ Secret
*****_ Empty directory
*****_ Cloned Git repo

**** Deployment
*****_ Resource Manager template
*****_ YAML file
**** Resource allocation
*****_ CPUs, memory, and optionally GPUs

*** Common scenarios
**** Divide a single functional task
*****_ Postman tests container + Web API container
*****_ Application container + logging container
*****_ Application container + monitoring container
*****_ Front-end container + backend 3rd party API container\n(think SigningHub) 
**** Separate teams and resource requirements


** (Run with) Restart policies
***_ Containers billed by the second. Only charged for the compute resources used.
*** Container restart policy
**** Always
*****_ Default
*****_ Containers in group are always restarted
**** Never
*****_ Containers run at most once.\n...never restarted
**** OnFailure
*****_ Containers run at least once...
*****_ Restarted when terminates with nonzero exit code.
*** Run to completion
****_ If container with Never or OnFailure stops status is set to Terminated.

* Environment variables
** Secure values
***_ Supported for both Linux and Windows
***_ Hold sensitive information (passwords, keys)
***_ Not visible from Azure Portal or CLI.
***_ **secureValue** rather than **value** in YAML.

* Mount an Azure file share in Azure Container Instances
** Limitations
** Deploy container and mount volume
*** Deploy container and mount volume - YAML
** Mount multiple volumes
@endmindmap
