@startmindmap "Azure Cache for Redis"


+ Supported\nArchitectural Patterns
++ Data Cache\n(Cache-aside)
+++_ Data loaded into cache as needed
+++_ System updates the database and matching cache data
++ Content Cache
+++_ Static content like headers, footers, banners shouldn't change often.
+++_ In-memory cache provides quick access
++ Session Store
+++_ Use cookie as a key to data located in Session (cache) store
+++_ eg. Shopping carts and user history data.
++ Job and Message Queuing
+++_ Long running requests queued to be processed
+++_ While running don't need to be requested again
++ Distributed Transactions
+++_ Azure Cache for Redis supports executing a batch of commands as a single transaction

+_ **Clients need the host name, port, and an access key for the cache**
++_ The host name is like sportsresults.redis.cache.windows.net
++_ The access key acts as a password for your cache

+ Plans
++[#lightblue] Open Source
+++ Basic Tier
++++_ OSS Redis cache on a single VM
++++_ Suitable for development/test and noncritical workloads
+++ Standard Tier
++++_ OSS Redis cache on two VMs in a replicated configuration
+++ Premium Tier
++++_ High-performance OSS Redis caches
++++_ Higher throughput, lower latency, better availability, and more features
++[#lightpink] Redis Labs
+++ Enterprise Tier
++++_ High-performance caches powered by Redis Enterprise software
++++_ Redis modules support (RediSearch, RedisBloom, RedisTimeSeries)
++++_ Higher availability than the Premium tier
+++ Enterprise Flash Tier
++++_ Cost-effective large caches powered by Redis Enterprise software
++++_ Extends Redis data storage to nonvolatile memory
++++_ Reduces overall per-GB memory cost

+ Best Practices
++ Always place your cache in the same region as your application
++ Standard tier or higher is required for production systems

@endmindmap
