@startmindmap
+ Apps

++ Anki

'https://www.youtube.com/watch?v=1mJKMNpwSiA
++ RemNotes
+++_ **Strength:** Seems very good for memorizing code sections
+++_ However there are some short commings
++ Mem.io

++ Notion

++ Obsidian

++ Roam

@endmindmap