@startmindmap

+ ???

' ++ New Learning Concepts
' +++_ Listings... requires incremental investigation
' +++_ How does it work for you?

' +++ Mind mapping
' +++ Concept maps
' +++ Flash cards

' ++ Notate current learning strategy
' +++_ In a form you can follow


+ Mistakes

++ Strategy
+++_ Did not map out learning path at the beginning
+++_ No structured step by step system
+++_ Too much detailed admin is a killer... keep it simple

+++ Big Picture
++++_ What are the connections?\n...How can I connect the concepts?
++++_ What are the cross cutting concerns\n...how can I learn them seperately?

++ Flashcards
+++_ Generated flash cards
++++_ **FIX**
+++++_ Studying material first helps target the right flash card questions
+++++_ Focus on what you need to memorize. Not necessdary if you already know it
+++_ TOO MANY to study
++++_ **FIX** See above
+++_ Started revising too late!
+++_ Had little knowledge of...
++++_ how to compile them 
++++_ the apps
++++_ how to use them effectively
+++_ **FIX** Know your apps... learn how to use them for your own means\n...Decide on your tools!
+++_ Long answers are really hard to memorize
++++_ **FIX** Keep them short
++++_ Decide on the right card types for the right content.

++ Practice Tests
+++_ Started too late!

++ Notes
+++_ Notion notes are a waste of time! You never review them.
+++_ **FIX** Use Notion as a project board and links to other resources\n...

@endmindmap