@startmindmap

+_ OAuth 2.0 and OpenID Connect\nstandard-compliant authentication service
++_ Work or school accounts (Azure Active Directory)
++_ Personal Microsoft account (Skype, Xbox, Outlook.com)
++_ Social or local accounts (Azure Active Directory B2C)

+ Components
++ OAuth 2.0 and OpenID Connect\nstandard-compliant authentication service
+++_ Work or school accounts (Azure Active Directory)
+++_ Personal Microsoft account (Skype, Xbox, Outlook.com)
+++_ Social or local accounts (Azure Active Directory B2C)
++ Application management portal (Azure portal)

-- Open-source libraries
---_ **Microsoft Authentication Libraries (MSAL)**
---_ Support for other standards-compliant libraries
--_ Application Configuration API\nMicrosoft Graph
--_ PowerShell\nAutomate devOps tasks


* Microsoft identity platform
** Build applications for users and customers
*** Sign in with Microsoft identities or social accounts
*** Provide authorized access to APIs
**** Own APIs
**** Microsoft APIs like Microsoft Graph

**_ Modern innovations for developers
*** Passwordless authentication
*** Step-up authentication
*** Conditional Access
@endmindmap
