@startmindmap "AZ-400 - Explore Azure Pipelines"

title Develop Azure compute solutions (25–30%)
caption Develop Azure compute solutions (25–30%)
center footer Develop Azure compute solutions (25–30%)

<style>

    mindMapDiagram {
        
        LineColor lightblue
        RoundCorner 5
        BackgroundColor white
        Shadowing 2.0

        node {
            FontColor white
            LineColor black
            BackgroundColor black
            Shadowing 2.0
            RoundCorner 25
        }
        :depth(0) {
            FontColor black
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor black
            BackgroundColor darkgrey
            Shadowing 2.0
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>


+ Content

++ Containerized Solutions
+++ Azure Container Registry (ACR)
++++ Pull images from registry
+++++_ to
++++++ Scalable orchestration systems
++++++ Azure services
++++ Tiers
+++++_ Basic
+++++_ Standard
+++++_ Premium
-- App Service Web Apps
-- Azure Functions
++++ ACR Tasks
+++++_ Image building,\nmaintenance
++++++_ Linux
++++++_ Windows
++++++_ ARM
+++++_ Supported\ntask scenarios
++++++ Quick Tasks
+++++++_ Simple build and push
++++++_ Automatically\ntriggered tasks
+++++++ Multi-step task
++++++++_ Multi image
++++++++_ YAML file
+++++++ Scheduled tasks 



' ++++[#Orange] Study

@endmindmap