@startmindmap

* How Azure Content Delivery Network works
** A user requests a file
*** Using a URL with a special domain name, such as <endpoint name>.azureedge.net
*** DNS routes the request to the best performing POP location
** If file not in edge servers' cache
*** POP requests the file from the origin server
*** Origin server can be Azure Web App, Azure Cloud Service, Azure Storage account, or any publicly accessible web server
*** Origin server returns the file to the edge server in the POP
** Edge server caches the file
*** File remains cached until TTL specified by HTTP headers expires
*** Default TTL is seven days if not specified
** Additional users requesting the same file
*** If TTL not expired, edge server returns the file directly from cache

@endmindmap
