@startmindmap
skinparam defaultFontName Arial

* Azure CDN
** Requirements
*** CDN profile
**** Collection of CDN endpoints
*** CDN endpoint
**** Represents specific configuration
**** Content delivery behavior and access
*** Multiple profiles for organization
**** Internet domain, web application, or criteria
*** Mix of pricing tiers requires multiple profiles
** Limitations
*** Default limits per Azure subscription
**** CDN profiles creation
**** Endpoints creation in a CDN profile
**** Custom domains mapped to an endpoint
*** More information at CDN limits
** Azure CDN Features
*** Dynamic site acceleration
*** CDN caching rules
*** HTTPS custom domain support
*** Azure diagnostics logs
*** File compression
*** Geo-filtering
*** Complete list at Compare Azure CDN product features
** Control cache behavior
*** Cached resource can be out-of-date or stale
*** Caching mechanism controls refresh
*** Freshness based on age or cache setting
*** Browser reloads webpage with cached resources
*** Caching behavior controlled by Azure CDNs
**** Caching rules
***** Global or custom rules
***** Apply to specific paths and file extensions
**** Query string caching
***** Configurable response to query strings
****** No effect on uncached files
**** Azure CDN Standard for Microsoft caching rules
***** Ignore query strings (default)
***** Bypass caching for query strings
***** Cache every unique URL
****** Inefficient for unique URL requests
**** Change settings in Endpoint pane
@endmindmap
