@startmindmap "Access Tiers"

' Azure Blob Storage
* Azure Blob Storage

** Blob storage is designed for:
***_ Serving images or documents directly to a browser.
***_ Storing files for distributed access.
***_ Streaming video and audio.
***_ Writing to log files.
***_ Storing data for backup and restore, disaster recovery, and archiving.
***_ Storing data for analysis by an on-premises or Azure-hosted service.

** Accessing Blob storage:
***_ HTTP/HTTPS
***_ Azure Storage REST API
***_ Azure PowerShell
***_ Azure CLI
***_ Azure Storage client library

** Azure Storage Account
***_ Top-level container for Azure Blob storage
***_ Provides a unique namespace
***_ Accessible worldwide over HTTP/HTTPS

** Types of Storage Accounts
*** Standard (recommended for most scenarios)
*** Premium (higher performance using solid-state drives)
****_ Block blobs
****_ Page blobs
****_ File shares

** Access Tiers for Blob Data
*** Hot (frequent access, highest storage costs, lowest access costs)
*** Cool (infrequent access, lower storage costs, higher access costs)
*** Archive (data tolerance for latency, cost-effective but more expensive access)

** Switching Access Tiers
*** Can switch between Hot, Cool, and Archive tiers

@endmindmap
