@startmindmap
* Azure Functions
** Serverless Solution
*** Write less code
*** Manage less infrastructure
*** Save on costs
** Triggers
*** Initiate code execution
** Bindings
*** Simplify input and output handling
** Usage Scenarios
*** Web APIs
*** Database changes
*** IoT data streams
*** Message queues
** Integration and Automation
*** Solve integration problems
*** Automate business processes
*** Define input, actions, conditions, and output
** Azure Functions vs. Logic Apps
*** Azure Functions
**** Code-first (imperative)
**** Built-in binding types
**** Each activity is an Azure function
**** Monitor with Azure Application Insights
**** Management via REST API and Visual Studio
**** Run in Azure or locally
*** Logic Apps
**** Designer-first (declarative)
**** Connectors
**** Collection of pre-built actions
**** Monitor with Azure Monitor Logs
**** Management via Azure Portal, REST API, PowerShell, and Visual Studio
**** Run in Azure, locally, or on premises
** Azure App Service WebJobs with WebJobs SDK
*** Code-first integration service
*** Built on Azure App Service
*** Source control integration
*** Authentication
*** Monitoring with Application Insights
** Azure Functions vs. WebJobs with WebJobs SDK
*** Functions
**** Serverless app model
**** Automatic scaling
**** Test in browser
**** Pay-per-use pricing
*** WebJobs
**** No automatic scaling
**** No browser testing
**** Different pricing model
@endmindmap