

# In Azure go to the created key vault
# Open your secret
# In Network developer tools look for a request starting with "versions?api-version=..."
# If you copy the link address you will get the full URL
# You'll get a 201 OK
# Use https://jwt.ms/ to check your token

@keyvault=robazkeyvault

### Example Secrets
@vaultUri=https://{{keyvault}}.vault.azure.net/secrets/ExamplePassword/versions?api-version=7.0&maxresults=25&_=1686213446753
@token=Bearer 
GET {{vaultUri}}  HTTP/1.1  
# Authorization: {{token}}

### Example Keys
@vaultUri=https://{{keyvault}}.vault.azure.net/keys/ExamplePassword/versions?api-version=7.0&maxresults=25&_=1686213446753
@token=Bearer 
GET {{vaultUri}}  HTTP/1.1  
Authorization: {{token}}