@startmindmap " Playloads and Serialization"
* Service Bus\nMessage Payloads\nand Serialization
** Message Structure
*** Metadata\n(Key-Value Pair Properties)
****_ Describes Payload
****_ Handling Instructions to Service Bus and applications
**** Broker Properties
*****_ To
*****_ ReplyTo
*****_ ReplyToSessionId
*****_ MessageId
*****_ CorrelationId
*****_ SessionId
**** User Properties
*****_ Application defined key-value pairs
*** Payload (Opaque, Binary Block)
**** ContentType (MIME content-type)
**** Serialization
*****_ .NET Framework
*****_ Legacy SBMP Protocol
*****_ AMQP Protocol
** Object Model (for .NET and Java Clients)
** Binary Payload Section


** Routing and Correlation\nPatterns
*** Simple Request/Reply
*** Multicast Request/Reply
*** Multiplexing
*** Multiplexed Request/Reply
** Routing and Namespacing
*** Autoforward Chaining
*** Topic Subscription Rules
*** Azure LogicApps
*** To Property (Reserved for Future Use)
** Payload Serialization
*** ContentType Property
*** Serialization Control
** Explicit Object Serialization Control
@endmindmap
