@startmindmap
* Azure Queue Storage
** Storing Messages
*** Large numbers of messages
** Accessing Messages
*** Authenticated calls using HTTP or HTTPS
** Queue Message Size
*** Up to 64 KB in size
** Queue Capacity
*** Millions of messages
** Purpose of Queues
*** Creating backlog of work for asynchronous processing
** URL Format
*** https://<storage account>.queue.core.windows.net/<queue>
** Access to Azure Storage
*** Through a storage account
** Queue Content
*** Set of messages
** Queue Name Requirement
*** All lowercase
** Message Size
*** Up to 64 KB
** Maximum Time-to-live
*** Any positive number or -1 (no expiry)
** Default Time-to-live
*** Seven days
@endmindmap
