@startmindmap
* Azure Queue Storage
** Purpose
***_ Creating backlog of work for asynchronous processing
** Storing Messages
***_ Large numbers of messages
*** Accessing Messages
****_ Authenticated calls using HTTP or HTTPS
***_ Queue Message Size - Up to 64 KB in size
***_ Queue Capacity - Millions of messages
** URL Format
***_ https://<storage account>.queue.core.windows.net/<queue>
** Access
***_ Through a storage account
** Queue Content
***_ Queue Name - lowercase
*** Set of messages
**** Message
*****_ Maximum Time-to-live - Any positive number or -1 (no expiry)
***** Default Time-to-live
******_ Seven days
@endmindmap
